load("@rules_scala_annex//rules:scala.bzl", "scala_library")

scala_library(
    name = "lib-srcjar",
    srcs = ["example.srcjar"],
    scala = "//scala:2_13",
)

scala_library(
    name = "lib-sources-jar",
    srcs = ["example-sources.jar"],
    scala = "//scala:2_13",
)

scala_library(
    name = "lib-src-jar",
    srcs = ["example-src.jar"],
    scala = "//scala:2_13",
)
