module(name = "rules_scala_annex_tests")

bazel_dep(name = "protobuf", version = "29.3")
bazel_dep(name = "rules_java", version = "8.9.0")
bazel_dep(name = "rules_jvm_external", version = "6.5")
bazel_dep(name = "rules_scala_annex")
local_path_override(
    module_name = "rules_scala_annex",
    path = "..",
)

register_toolchains(
    "//:repository_default_toolchain_21_definition",
    "//dependencies/indirect:test_zinc_2_13_direct_deps_off",
    "//dependencies/indirect:test_zinc_2_13_used_deps_off",
    "//plugins/kind-projector:test_zinc_2_13_with_kind_projector",
    "//plugins/semanticdb:scala_2_13_with_semanticdb",
    "//plugins/semanticdb:scala_3_with_semanticdb",
    "//scala:test_bootstrap_2_12",
    "//scala:test_bootstrap_2_13",
    "//scala:test_bootstrap_3",
    "//scala:test_zinc_2_12",
    "//scala:test_zinc_2_13",
    "//scala:test_zinc_3",
    "//scala:test_zinc_2_13_fatal_deprecation_opt",
    "//scala:test_zinc_2_13_log_level_debug",
)

# Please ensure these stay up-to-date with the versions in `/rules/scala/versions.bzl`,
# `/tests/MODULE.bazel`, and `/MODULE.bazel`. Unfortunately, `MODULE.bazel` files can't call `load`,
# so we have to copy them here.
scala_2_12_version = "2.12.19"

scala_2_13_version = "2.13.15"

scala_3_version = "3.5.2"

scalapb_version = "0.11.17"

zinc_version = "1.10.4"

specs2_version = "4.20.9"

scalatest_version = "3.2.19"

scalacheck_version = "1.18.1"

annex_test = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
annex_test.install(
    name = "annex_test",
    artifacts = [
        "com.novocode:junit-interface:jar:0.11",
        "com.thesamet.scalapb:lenses_2.13:{}".format(scalapb_version),
        "com.thesamet.scalapb:scalapb-runtime_2.13:{}".format(scalapb_version),
        "junit:junit:4.12",
        "org.hamcrest:hamcrest-core:1.3",
        "org.scala-lang:scala-compiler:{}".format(scala_2_13_version),
        "org.scala-lang:scala-library:{}".format(scala_2_13_version),
        "org.scala-lang:scala-reflect:{}".format(scala_2_13_version),
        "org.scala-lang:scala3-compiler_3:{}".format(scala_3_version),
        "org.scala-lang:scala3-library_3:{}".format(scala_3_version),
        "org.scala-lang.modules:scala-xml_2.13:2.3.0",
        "org.scala-sbt:compiler-interface:{}".format(zinc_version),
        "org.scala-sbt:util-interface:{}".format(zinc_version),
        "org.scala-sbt:util-logging_2.13:{}".format(zinc_version),
        "org.scala-sbt:zinc-compile-core_2.13:{}".format(zinc_version),
        "org.scala-sbt:zinc-persist_2.13:{}".format(zinc_version),
        "org.scalacheck:scalacheck_2.13:{}".format(scalacheck_version),
        "org.scalactic:scalactic_2.13:{}".format(scalatest_version),
        "org.scalameta:semanticdb-scalac_2.13.14:4.9.9",
        "org.scalatest:scalatest_2.13:{}".format(scalatest_version),
        "org.specs2:specs2-common_2.13:{}".format(specs2_version),
        "org.specs2:specs2-core_2.13:{}".format(specs2_version),
        "org.specs2:specs2-matcher_2.13:{}".format(specs2_version),
        "org.typelevel:kind-projector_2.13.14:0.13.3",
    ],
    fetch_sources = True,
    lock_file = "//:annex_test_install.json",
    repositories = [
        "https://repo.maven.apache.org/maven2",
        "https://maven-central.storage-download.googleapis.com/maven2",
        "https://mirror.bazel.build/repo1.maven.org/maven2",
    ],
)

# The compiler bridge has a dependency on compiler-interface, which has a dependency on the Scala 2
# library. We need to set this to neverlink = True to avoid this the Scala 2 library being pulled
# onto the Scala 3, and other Scala versions like 2.12, compiler classpath during runtime.
annex_test.artifact(
    name = "annex_test",
    artifact = "scala3-sbt-bridge",
    group = "org.scala-lang",
    neverlink = True,
    version = scala_3_version,
)

# The compiler bridge has a dependency on compiler-interface, which has a dependency on the Scala 2
# library. We need to set this to neverlink = True to avoid this the Scala 2 library being pulled
# onto the Scala 3, and other Scala versions like 2.12, compiler classpath during runtime.
annex_test.artifact(
    name = "annex_test",
    artifact = "compiler-bridge_2.13",
    group = "org.scala-sbt",
    neverlink = True,
    version = zinc_version,
)
use_repo(annex_test, "annex_test")

annex_test_2_12 = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
annex_test_2_12.install(
    name = "annex_test_2_12",
    artifacts = [
        "org.scala-lang:scala-compiler:{}".format(scala_2_12_version),
        "org.scala-lang:scala-library:{}".format(scala_2_12_version),
        "org.scala-lang:scala-reflect:{}".format(scala_2_12_version),
        "org.specs2:specs2-common_2.12:{}".format(specs2_version),
        "org.specs2:specs2-core_2.12:{}".format(specs2_version),
        "org.specs2:specs2-matcher_2.12:{}".format(specs2_version),
        "org.scalatest:scalatest_2.12:{}".format(scalatest_version),
        "org.scalacheck:scalacheck_2.12:{}".format(scalacheck_version),
    ],
    fetch_sources = True,
    lock_file = "//:annex_test_2_12_install.json",
    repositories = [
        "https://repo.maven.apache.org/maven2",
        "https://maven-central.storage-download.googleapis.com/maven2",
        "https://mirror.bazel.build/repo1.maven.org/maven2",
    ],
)

# The compiler bridge has a dependency on compiler-interface, which has a dependency on the Scala 2
# library. We need to set this to neverlink = True to avoid this the Scala 2 library being pulled
# onto the Scala 3, and other Scala versions like 2.12, compiler classpath during runtime.
annex_test_2_12.artifact(
    name = "annex_test_2_12",
    artifact = "compiler-bridge_2.12",
    group = "org.scala-sbt",
    neverlink = True,
    version = zinc_version,
)
use_repo(annex_test_2_12, "annex_test_2_12")

http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

# We fetch these via `http_file` instead of `rules_jvm_external` because they're used in
# `scala_import` targets. By them not having `JavaInfo` or any extra providers added, we test that
# `scala_import` doesn't rely on any of this information.
http_file(
    name = "shapeless_jar",
    downloaded_file_path = "shapeless.jar",
    sha256 = "072c83eca9996aed92310dc7225cfc313edc7b74a3a96e2bf25459ebfc04ac96",
    urls = ["https://repo.maven.apache.org/maven2/com/chuusai/shapeless_2.13/2.3.7/shapeless_2.13-2.3.7.jar"],
)

http_file(
    name = "shapeless_srcjar",
    downloaded_file_path = "shapeless-sources.jar",
    sha256 = "72c5bd08c7d97ccefc2fe871c47dd6aed4b12ba19f616e3ac30946907d1cc4d2",
    urls = ["https://repo.maven.apache.org/maven2/com/chuusai/shapeless_2.13/2.3.7/shapeless_2.13-2.3.7-sources.jar"],
)
