workspace(name = "rules_scala_annex_test")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")

# skylib

bazel_skylib_tag = "1.7.1"

bazel_skylib_sha256 = "bc283cdfcd526a52c3201279cda4bc298652efa898b10b4db0837dc51652756f"

http_archive(
    name = "bazel_skylib",
    sha256 = bazel_skylib_sha256,
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/{tag}/bazel-skylib-{tag}.tar.gz".format(tag = bazel_skylib_tag),
        "https://github.com/bazelbuild/bazel-skylib/releases/download/{tag}/bazel-skylib-{tag}.tar.gz".format(tag = bazel_skylib_tag),
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

# protobuf

protobuf_tag = "3.19.6"

protobuf_sha256 = "387e2c559bb2c7c1bc3798c4e6cff015381a79b2758696afcbf8e88730b47389"

http_archive(
    name = "com_google_protobuf",
    sha256 = protobuf_sha256,
    strip_prefix = "protobuf-{}".format(protobuf_tag),
    type = "zip",
    url = "https://github.com/protocolbuffers/protobuf/archive/v{}.zip".format(protobuf_tag),
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()

# rules_java
http_archive(
    name = "rules_java",
    sha256 = "8afd053dd2a7b85a4f033584f30a7f1666c5492c56c76e04eec4428bdb2a86cf",
    urls = [
        "https://github.com/bazelbuild/rules_java/releases/download/7.6.5/rules_java-7.6.5.tar.gz",
    ],
)

load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")

rules_java_dependencies()

rules_java_toolchains()

register_toolchains("//:repository_default_toolchain_21_definition")

local_repository(
    name = "rules_scala_annex",
    path = "../",
)

# rules_jvm_external
rules_jvm_external_tag = "6.1"

http_archive(
    name = "rules_jvm_external",
    sha256 = "42a6d48eb2c08089961c715a813304f30dc434df48e371ebdd868fc3636f0e82",
    strip_prefix = "rules_jvm_external-{}".format(rules_jvm_external_tag),
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/{}.zip".format(rules_jvm_external_tag),
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load(
    "@rules_scala_annex//rules/scala:workspace.bzl",
    "scala_register_toolchains",
    "scala_repositories",
)

# Scala 2.13 and 3
scala_repositories()

load("@annex//:defs.bzl", annex_pinned_maven_install = "pinned_maven_install")

annex_pinned_maven_install()

scala_register_toolchains()

#  Scala 2.12
load("@rules_scala_annex//rules/scala:workspace_2_12.bzl", "scala_2_12_repositories")

scala_2_12_repositories()

load("@annex_2_12//:defs.bzl", annex_2_12_pinned_maven_install = "pinned_maven_install")

annex_2_12_pinned_maven_install()

load(
    "@rules_scala_annex//rules/scala_proto:workspace.bzl",
    "scala_proto_register_toolchains",
    "scala_proto_repositories",
)

scala_proto_repositories()

scala_proto_register_toolchains()

load("@annex_proto//:defs.bzl", annex_proto_pinned_maven_install = "pinned_maven_install")

annex_proto_pinned_maven_install()

load("@rules_scala_annex//rules:external.bzl", "scala_import_external")
load("@rules_scala_annex//rules:rules_scala.bzl", "emulate_rules_scala")

scala_import_external(
    name = "scalatest_2_13",
    jar_sha256 = "c5d283a5ec028bf06f83d70e2b88d70a149dd574d19e79e8389b49483914b08b",
    jar_urls = ["https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.13/3.2.9/scalatest_2.13-3.2.9.jar"],
    licenses = ["notice"],
)

emulate_rules_scala(
    extra_deps = [
        "@annex//:org_scala_lang_scala_reflect",
        "@annex_test//:org_scala_lang_modules_scala_xml_2_13",
    ],
    scala = "@//scala:2_13",
    scalatest = "@scalatest_2_13//jar",
)

load("@rules_scala_annex//rules/scalafmt:workspace.bzl", "scalafmt_default_config", "scalafmt_repositories")

scalafmt_repositories()

load("@annex_scalafmt//:defs.bzl", annex_scalafmt_pinned_maven_install = "pinned_maven_install")

annex_scalafmt_pinned_maven_install()

scalafmt_default_config()

# 2.13 test dependencies
load(":workspace.bzl", "test_dependencies")

test_dependencies()

load("@annex_test//:defs.bzl", annex_test_pinned_maven_install = "pinned_maven_install")

annex_test_pinned_maven_install()

# 2.12 test dependencies
load(":workspace_2_12.bzl", "test_2_12_dependencies")

test_2_12_dependencies()

load("@annex_test_2_12//:defs.bzl", annex_test_2_12_pinned_maven_install = "pinned_maven_install")

annex_test_2_12_pinned_maven_install()

jvm_maven_import_external(
    name = "junit",
    artifact = "junit:junit:4.12",
    artifact_sha256 = "59721f0805e223d84b90677887d9ff567dc534d7c502ca903c0c2b17f05c116a",
    licenses = ["notice"],
    server_urls = ["https://repo.maven.apache.org/maven2"],
)

jvm_maven_import_external(
    name = "hamcrest_core",
    artifact = "org.hamcrest:hamcrest-core:1.3",
    artifact_sha256 = "66fdef91e9739348df7a096aa384a5685f4e875584cce89386a7a47251c4d8e9",
    licenses = ["notice"],
    server_urls = ["https://repo.maven.apache.org/maven2"],
)

jvm_maven_import_external(
    name = "junit_interface",
    artifact = "com.novocode:junit-interface:jar:0.11",
    artifact_sha256 = "29e923226a0d10e9142bbd81073ef52f601277001fcf9014389bf0af3dc33dc3",
    licenses = ["notice"],
    server_urls = ["https://repo.maven.apache.org/maven2"],
)

bind(
    name = "default_scala",
    actual = "//scala:zinc_2_13",
)

http_file(
    name = "shapeless_jar",
    downloaded_file_path = "shapeless.jar",
    sha256 = "072c83eca9996aed92310dc7225cfc313edc7b74a3a96e2bf25459ebfc04ac96",
    urls = ["https://repo.maven.apache.org/maven2/com/chuusai/shapeless_2.13/2.3.7/shapeless_2.13-2.3.7.jar"],
)

http_file(
    name = "shapeless_srcjar",
    downloaded_file_path = "shapeless-sources.jar",
    sha256 = "72c5bd08c7d97ccefc2fe871c47dd6aed4b12ba19f616e3ac30946907d1cc4d2",
    urls = ["https://repo.maven.apache.org/maven2/com/chuusai/shapeless_2.13/2.3.7/shapeless_2.13-2.3.7-sources.jar"],
)

# rules_python - this is needed by rules_jvm_external for some reason
rules_python_tag = "0.33.2"

http_archive(
    name = "rules_python",
    sha256 = "e3f1cc7a04d9b09635afb3130731ed82b5f58eadc8233d4efb59944d92ffc06f",
    strip_prefix = "rules_python-{}".format(rules_python_tag),
    url = "https://github.com/bazelbuild/rules_python/releases/download/{}/rules_python-{}.tar.gz".format(rules_python_tag, rules_python_tag),
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()
