workspace(name = "rules_scala_annex_test")

load("@rules_scala_annex//rules:external.bzl", "scala_import_external")
load("@rules_scala_annex//rules:rules_scala.bzl", "emulate_rules_scala")

scala_import_external(
    name = "scalatest_2_13",
    jar_sha256 = "c5d283a5ec028bf06f83d70e2b88d70a149dd574d19e79e8389b49483914b08b",
    jar_urls = ["https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest_2.13/3.2.9/scalatest_2.13-3.2.9.jar"],
    licenses = ["notice"],
)

emulate_rules_scala(
    extra_deps = [
        "@annex_test//:org_scala_lang_scala_reflect",
        "@annex_test//:org_scala_lang_modules_scala_xml_2_13",
    ],
    scalatest = "@scalatest_2_13//jar",
)
