load("@rules_scala_annex//rules:scala.bzl", "scala_binary")

scala_binary(
    name = "lib",
    srcs = ["Example.scala"],
    scala_toolchain_name = "test_zinc_2_13_log_level_debug",
    deps = [],
)
