load("@rules_scala_annex//rules:scala.bzl", "scala_library")

scala_library(
    name = "special_characters",
    srcs = [],
    resources = glob(["**/*.txt"]),
    scala_toolchain_name = "test_zinc_2_13",
)
