#!/bin/bash -e
. "$(dirname "$0")"/../common.sh

# We use nouse_action_cache + bazel shutdown here in order to prevent the skyframe
# cache and the persistent action cache from being used and thus getting the
# warning we want printed, printed. The alternative is to bazel clean, which
# takes much longer.
bazel shutdown

assert_jvm_flag_applied() {
    local mnemonic="$1"
    local target="$2"
    local output

    set +x

    if ! output="$(
        bazel build \
            --modify_execution_info="${mnemonic}=+no-cache" \
            --nouse_action_cache \
            --strategy="${mnemonic}=sandboxed" \
            "${target}" 2>&1
    )"; then
        printf "%s\n" "${output}"
        set -x
        return 1
    fi

    if ! grep -Fq "annex.jvm_flags.test = enabled" <<<"${output}"; then
        printf "%s\n" "${output}"
        set -x
        return 1
    fi
    set -x
}

assert_jvm_flag_applied "BootstrapScalaCompile" ":bootstrap_good"
! bazel build :bootstrap_bad

assert_jvm_flag_applied "ScalaCompile" ":zinc_good"
! bazel build :zinc_bad

assert_jvm_flag_applied "ScalaFmt" ":scalafmt_good"
! bazel build :scalafmt_bad
