load("@rules_scala_annex//rules:scala.bzl", "scala_library")

scala_library(
    name = "welcome_to_bloop",
    srcs = ["welcome_to_bloop.scala"],
    scala_toolchain_name = "test_zinc_2_13",
    tags = ["manual"],
)
