load(
    ":replace_source_target_with_release_test.bzl",
    "replace_source_target_with_release_test_suite",
)

replace_source_target_with_release_test_suite(name = "replace_source_target_with_release_test")
