load("@rules_scala_annex//rules:scala.bzl", "scala_library")

scala_library(
    name = "error_reporting_2_13",
    srcs = ["ErrorReporting.scala"],
    scala = "//scala:2_13",
    tags = ["manual"],
)

scala_library(
    name = "error_reporting_bootstrap_3",
    srcs = ["ErrorReporting.scala"],
    scala = "//scala:bootstrap_3",
    tags = ["manual"],
)

scala_library(
    name = "error_reporting_zinc_3",
    srcs = ["ErrorReporting.scala"],
    scala = "//scala:zinc_3",
    tags = ["manual"],
)
