load("@rules_scala_annex//rules:scala.bzl", "scala_library")

scala_library(
    name = "error_reporting_2_13",
    srcs = ["ErrorReporting.scala"],
    scala_toolchain_name = "test_zinc_2_13",
    tags = ["manual"],
)

scala_library(
    name = "error_reporting_bootstrap_3",
    srcs = ["ErrorReporting.scala"],
    scala_toolchain_name = "test_bootstrap_3",
    tags = ["manual"],
)

scala_library(
    name = "error_reporting_zinc_3",
    srcs = ["ErrorReporting.scala"],
    scala_toolchain_name = "test_zinc_3",
    tags = ["manual"],
)
