name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - lucid-master
jobs:
  build-lint-and-test:
    runs-on: ${{ matrix.os }}
    env:
      BAZEL_VERSION: ${{ matrix.bazel_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        bazel_version: [7.2.0]
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/ci.sh build
      - run: ./scripts/ci.sh lint
      - run: ./scripts/ci.sh test
